task: motion_analysis_bench
tag: video_qa
dataset_path: json
dataset_kwargs:
  data_files:
    test:
      - /projects/aclab/shayda/vqa_benchmarks/nextqa_remainder_part5.jsonl
test_split: test
output_type: generate_until
doc_to_visual: !function utils.motion_analysis_bench_doc_to_visual
doc_to_text: !function utils.motion_analysis_bench_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.motion_analysis_bench_process_results
metric_list:
  - metric: motion_analysis_bench_acc
    aggregation: !function utils.motion_analysis_bench_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's letter from the given choices directly."
  gpt4v:
    pre_prompt: ""
    post_prompt: "Answer the question with A, B, C, D, or E."
  llava_vid:
    pre_prompt: ""
    post_prompt: "The best answer is:"
metadata:
  version: 0.1