task: lostinplainsight_surprisingstatic
tag: video_qa
dataset_path: json
dataset_kwargs:
  data_files:
    test:
      - /projects/aclab/shayda/vqa_benchmarks/AVOE/evaluation_questions_surprising_static.jsonl
test_split: test
output_type: generate_until
doc_to_visual: !function utils.motion_analysis_bench_doc_to_visual
doc_to_text: !function utils.motion_analysis_bench_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 100
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.motion_analysis_bench_process_results_static
metric_list:
  - metric: motion_analysis_bench_acc
    aggregation: !function utils.motion_analysis_bench_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
metadata:
  version: 0.1